version: '3'

services:
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: mysql
    ports:
    - "3306:3306"
    restart: always
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_vol
    security_opt:
      - seccomp:unconfined

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    image: backend
    links:
      - mysql:mysql
    ports:
    - "8888:8080"
    depends_on:
      - mysql
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        echo "sleep over"
        java -jar -Dspring.profiles.active=prod /app.jar