version: '3'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-mysql
    image: db
    ports:
    - "3306:3306"
    restart: always
    command: --explicit_defaults_for_timestamp
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_vol

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-app
    image: backend
    links:
      - db:db
    ports:
    - "8888:8080"
    depends_on:
      - db
    command:
      - /bin/sh
      - -c
      - |
        sleep 30
        echo "sleep over"
        java -jar -Dspring.profiles.active=prod /app.jar